AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Kinesis Sample

Parameters:
  NamePrefix:
    Type: String

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Timeout: 10
      Tracing: Active
      Runtime: nodejs10.x
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt KinesisStream.Arn
            BatchSize: 100
            StartingPosition: LATEST

  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub "${NamePrefix}-kinesis-stream"
      RetentionPeriodHours: 24
      ShardCount: 1

Outputs:
  FunctionName:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
  StreamARN:
    Description: "Stream ARN"
    Value: !GetAtt KinesisStream.Arn
